### ISSUE TITLE
能加入PSD导入生成的功能吗

### ISSUE THREAD

**Issue by fukai7722** [panteng/wechat-h5-boilerplate#1]
参考这个项目

https://github.com/zswang/h5psd

**Comment by panteng** [comment]
@fukai7722 
感谢建议。
抱歉，我不会加入这个功能。
无论从我的公司代码规范层面，还是我的个人层面，都无法接受机器生成的代码。因为机器生成的代码在可读性、可靠性和可维护性上都不太好。作为一个开发者，我需要对自己的代码有完全的掌控。

**Comment by leafx** [comment]
为什么不直接回复 No.
