### ISSUE TITLE
不能循环滚动?

### ISSUE THREAD

**Issue by suxiaogang** [panteng/wechat-h5-boilerplate#10]
滚到最后一页,再往下不能到滚回第一页么?
(虽然易企秀什么的挺low的...)

**Comment by panteng** [comment]
修改Swiper相关部分的配置 
![qq 20160623160025](https://cloud.githubusercontent.com/assets/8369690/16295825/9e9e5514-395b-11e6-93a3-0aae5b7982d6.png)
