### ISSUE TITLE
初始化的BGM图标是播放状态的音乐图标

### ISSUE THREAD

**Issue by ryan4456** [panteng/wechat-h5-boilerplate#2]
初始化的BGM图标是播放状态的音乐图标。但是实际上是没有播放的。可以改成默认播放，或者默认不播放吧。

**Comment by panteng** [comment]
No no no,
移动端浏览器默认禁止音乐自动播放，必须在有用户触发行为后（比如点击屏幕）才能播放音乐。BGM图标开启状态表示用户触碰屏幕后将开始播放音乐，关闭状态则表示无论用户是否触碰，都不会播放音乐。

**Comment by jerrylau91** [comment]
有点意思。

**Comment by ryan4456** [comment]
实际上，用一些小的trick可以实现，移动设备浏览器自动播放音乐的。
![image](https://cloud.githubusercontent.com/assets/13702613/15345596/de1ca5f0-1ce2-11e6-83be-42703d673deb.png)

**Comment by panteng** [comment]
这个只在微信里可以，在微信外的移动浏览器就不行了。

**Comment by ryan4456** [comment]
嗯哼，你是对的。
