### ISSUE TITLE
添加第四屏后，第四屏是黑的，这是怎么回事

### ISSUE THREAD

**Issue by wangyupo** [panteng/wechat-h5-boilerplate#20]
![1499332963 1](https://user-images.githubusercontent.com/21337041/27904621-d620c72c-626f-11e7-8ac3-3210ad5328a5.png)
![1499332992 1](https://user-images.githubusercontent.com/21337041/27904622-d74639de-626f-11e7-8739-3773b24e1322.png)

**Comment by panteng** [comment]
也许是因为你还没有给第四屏写css样式。

**Comment by dongliang1993** [comment]
我也遇到这个问题了，求解答

**Comment by panteng** [comment]
Closed for now. Reopen if the reporter can provide more debug / error info.
