### ISSUE TITLE
请问是否和vue之间会有冲突

### ISSUE THREAD

**Issue by heohpro** [panteng/wechat-h5-boilerplate#22]
RT，在添加了vue之后，页面不能滑动翻页，绑定的是swiper-wrapper这个元素

> <div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide slide-1">
</div>

**Comment by panteng** [comment]
这个项目本质上是把各种第三方的库和插件组合在一起，你当然可以添加更多东西进来。

**Comment by heohpro** [comment]
你好，我绑定了vue之后，发现双向数据绑定的时候只能绑定初始化时的数据，在用axios拿数据之后页面双向绑定并没有更新，请问这是怎么回事呢？

**Comment by panteng** [comment]
抱歉，我没有办法给出答案。这个问题太笼统了。根据你的描述，我更感觉你的问题出在vue方面，而不是这个project上。
