### ISSUE TITLE
jquery.js:9843 Uncaught TypeError: slide.transform is not a function

### ISSUE THREAD

**Issue by zhongning7924** [panteng/wechat-h5-boilerplate#3]
我安装了jquey， 为什么调用不到啊

**Comment by panteng** [comment]
Sorry，是上次提交改出的bug，我正在修复

**Comment by panteng** [comment]
抱歉带来不便，已修复。
BUG原因来自swiper.jquery.js这个文件，貌似它对jquery的引用有点问题，换成swiper.jquery.umd.js就好了。

https://github.com/panteng/wechat-h5-boilerplate/releases/tag/v0.3.3

**Comment by zhongning7924** [comment]
thanks
