### ISSUE TITLE
有行代码， 觉得没必要，还望讲解

### ISSUE THREAD

**Issue by crane0** [panteng/wechat-h5-boilerplate#32]
在 animation-control.js中，这么一行代码，
$(this).attr('data-origin-class', $(this).attr('class'))

在clearAnimation方法中，又使用到了，
clearAnimation: function () {
        $('.animated').each(function () {
            $(this).css({ 'visibility': 'hidden' });
            $(this).attr('class', $(this).data('origin-class'));
        });
 }

这2行代码，我觉得删了也没有什么影响，请问他们的意思是什么，还望见谅
$(this).attr('data-origin-class', $(this).attr('class'))
 $(this).attr('class', $(this).data('origin-class'));

**Comment by panteng** [comment]
如果没记错的话，`$(this).attr('data-origin-class', $(this).attr('class'))`是为了记录该元素最开始的class name，并保存在data-origin-class里，方便后面clearAnimation的时候，直接把该元素恢复到最初始的状态。

**Comment by crane0** [comment]
发现区别了，如果没有这个，向上翻页时，之前的动画就不会再次触发。
谢谢
