### ISSUE TITLE
建议增加一下全屏背景图片的案例

### ISSUE THREAD

**Issue by bodyno** [panteng/wechat-h5-boilerplate#4]
建议增加一下全屏背景图片的案例
开发手机
很多时候全屏背景图片缩放问题很严重
建议可以做一个放在demo里面

**Comment by panteng** [comment]
“缩放问题”具体是指？

```
   .slide-1 {
       background: url('path_to_bg_image') center no-repeat;
       background-size: cover;
   }
```

这样不能解决吗？

**Comment by bodyno** [comment]
`
background-size: cover;
`

这样很容易变形

**Comment by panteng** [comment]
你确认一下，background-size: cover背景图是不会变形的，只会根据屏幕大小来截取背景图片。

**Comment by bodyno** [comment]
> Scale the background image to be as large as possible so that the background area is completely covered by the background image. Some parts of the background image may not be in view within the background positioning area

Maybe you are right.
