### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by hplc** [panteng/wechat-h5-boilerplate#6]
gulp dev 时报错：ReferenceError: Promise is not defined

CentOS 6.7
npm@1.3.6 

修复参照：http://stackoverflow.com/questions/32490328/gulp-autoprefixer-throwing-referenceerror-promise-is-not-defined
1. npm install es6-promise
2. 在gulpfile.js最前面加入：
   require('es6-promise').polyfill();

**Comment by panteng** [comment]
你使用最新的node.js和npm试下，npm最新的已经是3.9.5了
