### ISSUE TITLE
体积好大啊

### ISSUE THREAD

**Issue by cqgsm** [panteng/wechat-h5-boilerplate#8]

**Comment by panteng** [comment]
H5包含大量图片、音频，体积必然大。

**Comment by cqgsm** [comment]
demo里面光一个打包的bundle.min.js 237kb有点夸张了 加上图片，音乐随随便便就好几M，目前移动网络体验应该不是很好吧

**Comment by panteng** [comment]
如果觉得js太大，可以把jquery换成zepto，这样可以节省几十KB。但你说的“随随便便就好几M”，我认为主要原因不在bundle.min.js。所以我没有为了节省几十KB而选择Zepto，因为Zepto使用起来不如jQuery方便。

**Comment by LuoHuacheng** [comment]
换成zepto会报错。zepto.js:1625  Uncaught TypeError: Cannot read property 'fn' of undefined
